import { expect, it } from "vitest";
import { defineCatalog } from "@better-auth-ac/core";
import { caslModuleEtag, generateCaslModule, toCaslRules } from "../src/index.js";

it("emits deterministic allow and inverted deny rules", () => {
  const catalog = defineCatalog([
    {
      key: "order.refund",
      name: "Refund",
      description: "Refund an order.",
      group: "Orders",
      subject: "Order",
      action: "refund",
      scope: "organization",
      fields: ["id", "status"],
    },
    {
      key: "order.read",
      name: "Read",
      description: "Read an order.",
      group: "Orders",
      subject: "Order",
      action: "read",
      scope: "organization",
      fields: ["id", "total"],
    },
  ]);
  const payload = toCaslRules(catalog, [
    { key: "order.refund", effect: "DENY", allowed: false, reason: "Denied.", trace: [] },
    { key: "order.read", effect: "ALLOW", allowed: true, reason: "Allowed.", trace: [] },
  ]);
  expect(payload.rules).toEqual([
    { subject: "Order", action: "read", fields: ["id", "total"] },
    {
      subject: "Order",
      action: "refund",
      fields: ["id", "status"],
      inverted: true,
      reason: "Denied.",
    },
  ]);
});

it("generates a stable framework-agnostic module", () => {
  const catalog = defineCatalog([
    {
      key: "order.refund",
      name: "Refund",
      description: "Refund an order.",
      group: "Orders",
      subject: "Order",
      action: "refund",
      scope: "organization",
      fields: ["id", "status"],
    },
    {
      key: "iam.role.manage",
      name: "Manage roles",
      description: "Manage a role.",
      group: "IAM",
      subject: "Role",
      action: "manage",
      scope: "organization",
    },
  ]);

  expect(generateCaslModule(catalog)).toBe(`// Generated by @better-auth-ac/casl. Do not edit.

import type { MongoAbility } from "@casl/ability";

export const catalogVersion = "${catalog.version}";

export const Policy = {
  Iam: {
    Role: {
      Manage: {
        key: "iam.role.manage",
        action: "manage",
        subject: "Role",
      },
    },
  },
  Order: {
    Refund: {
      key: "order.refund",
      action: "refund",
      subject: "Order",
      fields: ["id", "status"],
    },
  },
} as const;

export type AppAbilities =
  | ["manage", "Role"]
  | ["refund", "Order"];
export type AppAbility = MongoAbility<AppAbilities>;
`);
});

it("rejects generated policy identifier collisions", () => {
  const catalog = defineCatalog([
    {
      key: "order-item.read",
      name: "Read",
      description: "Read an order item.",
      group: "Orders",
      subject: "OrderItem",
      action: "read",
      scope: "organization" as const,
    },
    {
      key: "order_item.read",
      name: "Read",
      description: "Read an order item.",
      group: "Orders",
      subject: "OrderItem",
      action: "read",
      scope: "organization" as const,
    },
  ]);

  expect(() => generateCaslModule(catalog)).toThrow(
    "Generated policy identifier collision: order-item.read and order_item.read",
  );
});

it("reports both keys in branch and leaf collisions", () => {
  const catalog = defineCatalog([
    {
      key: "foo.bar-baz.x",
      name: "Nested",
      description: "Nested permission.",
      group: "Test",
      subject: "Test",
      action: "read",
      scope: "organization",
    },
    {
      key: "foo.bar_baz",
      name: "Leaf",
      description: "Leaf permission.",
      group: "Test",
      subject: "Test",
      action: "read",
      scope: "organization",
    },
  ]);

  expect(() => generateCaslModule(catalog)).toThrow(
    "Generated policy identifier collision: foo.bar-baz.x and foo.bar_baz",
  );
});

it("rejects an invalid catalog version", () => {
  const catalog = defineCatalog([
    {
      key: "order.read",
      name: "Read",
      description: "Read an order.",
      group: "Orders",
      subject: "Order",
      action: "read",
      scope: "organization",
    },
  ]);

  expect(() => generateCaslModule({ ...catalog, version: "stale" })).toThrow(
    "Permission catalog version does not match its definitions",
  );
});

it("changes the artifact ETag when generated content changes", () => {
  expect(caslModuleEtag("first")).not.toBe(caslModuleEtag("second"));
});
