import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { afterEach, expect, it, vi } from "vitest";
import {
  checkPolicy,
  initPolicy,
  pullPolicy,
  runCli,
  validateArtifact,
  validateConfig,
  type CliIO,
} from "../src/cli.js";
import { caslModuleEtag } from "../src/index.js";

const artifact = `// Generated by @better-auth-ac/casl. Do not edit.

import type { MongoAbility } from "@casl/ability";

export const catalogVersion = "fnv1a-test";
export const Policy = {
} as const;
export type AppAbilities =
  | ["read", "Contact"];
export type AppAbility = MongoAbility<AppAbilities>;
`;

const temporaryDirectories: string[] = [];

async function project(): Promise<string> {
  const cwd = await mkdtemp(resolve(tmpdir(), "better-auth-ac-casl-"));
  temporaryDirectories.push(cwd);
  await writeFile(resolve(cwd, "package.json"), "{}\n");
  return cwd;
}

async function configure(cwd: string): Promise<void> {
  await writeFile(
    resolve(cwd, "better-auth-ac.json"),
    `${JSON.stringify({
      source: "https://api.example.com/iam/catalog/casl.ts",
      output: "src/generated/better-auth-ac.ts",
    })}\n`,
  );
}

function response(body: string | null, status = 200): Response {
  return new Response(body, { status, headers: { "content-type": "text/plain" } });
}

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((path) => rm(path, { recursive: true })));
});

it("initializes a config and protects it from non-interactive overwrite", async () => {
  const cwd = await project();
  const messages: string[] = [];
  const io: CliIO = { ask: vi.fn(), write: (message) => messages.push(message) };

  await initPolicy(
    {
      source: "https://api.example.com/iam/catalog/casl.ts",
      output: "src/generated/better-auth-ac.ts",
      pull: false,
    },
    { cwd, io },
  );

  await expect(
    initPolicy(
      {
        source: "https://other.example.com/casl.ts",
        output: "src/policy.ts",
        pull: false,
      },
      { cwd },
    ),
  ).rejects.toThrow("already exists");
  expect(await readFile(resolve(cwd, "better-auth-ac.json"), "utf8")).toContain("api.example.com");
  expect(messages.join("\n")).toContain("Commit better-auth-ac.json");
});

it("runs fully flagged init without prompts and prints the next steps", async () => {
  const cwd = await project();
  const messages: string[] = [];

  await runCli(
    [
      "init",
      "--source",
      "https://api.example.com/iam/catalog/casl.ts",
      "--output",
      "src/generated/better-auth-ac.ts",
      "--no-pull",
    ],
    { cwd, write: (message) => messages.push(message) },
  );

  expect(await readFile(resolve(cwd, "better-auth-ac.json"), "utf8")).toContain("api.example.com");
  expect(messages.join("\n")).toContain("bunx @better-auth-ac/casl pull");
});

it("pulls a valid artifact and uses its version as the next ETag", async () => {
  const cwd = await project();
  await configure(cwd);
  const firstFetch = vi.fn(async () => response(artifact));
  const secondFetch = vi.fn(async (_url: string | URL | Request, init?: RequestInit) => {
    expect(new Headers(init?.headers).get("if-none-match")).toBe(caslModuleEtag(artifact));
    return response(null, 304);
  });

  await expect(pullPolicy({ cwd, fetch: firstFetch as typeof fetch })).resolves.toBe("created");
  await expect(pullPolicy({ cwd, fetch: secondFetch as typeof fetch })).resolves.toBe("unchanged");
});

it("rejects an invalid artifact without replacing the local file", async () => {
  const cwd = await project();
  await configure(cwd);
  const output = resolve(cwd, "src/generated/better-auth-ac.ts");
  await mkdir(resolve(cwd, "src/generated"), { recursive: true });
  await writeFile(output, artifact);

  await expect(
    pullPolicy({ cwd, fetch: vi.fn(async () => response("not TypeScript")) as typeof fetch }),
  ).rejects.toThrow("not a generated");
  await expect(readFile(output, "utf8")).resolves.toBe(artifact);
});

it("fails check when the local artifact is stale", async () => {
  const cwd = await project();
  await configure(cwd);
  await mkdir(resolve(cwd, "src/generated"), { recursive: true });
  await writeFile(resolve(cwd, "src/generated/better-auth-ac.ts"), artifact);
  const changedArtifact = artifact.replace("fnv1a-test", "fnv1a-new");

  await expect(
    checkPolicy({
      cwd,
      fetch: vi.fn(async () => response(changedArtifact)) as typeof fetch,
    }),
  ).rejects.toThrow("is stale");
});

it("detects local changes that keep the catalog version", async () => {
  const cwd = await project();
  await configure(cwd);
  await mkdir(resolve(cwd, "src/generated"), { recursive: true });
  const modified = `${artifact}\n`;
  await writeFile(resolve(cwd, "src/generated/better-auth-ac.ts"), modified);

  await expect(
    checkPolicy({
      cwd,
      fetch: vi.fn(async (_url: string | URL | Request, init?: RequestInit) => {
        expect(new Headers(init?.headers).get("if-none-match")).toBe(caslModuleEtag(modified));
        return response(artifact);
      }) as typeof fetch,
    }),
  ).rejects.toThrow("is stale");
});

it("rejects executable code outside the generated artifact format", () => {
  expect(() => validateArtifact(`${artifact}\nfetch("https://example.com");\n`)).toThrow(
    "contains code outside",
  );
});

it("does not send authorization over remote HTTP or persist URL credentials", () => {
  expect(() =>
    validateConfig({
      source: "http://api.example.com/iam/catalog/casl.ts",
      output: "src/generated.ts",
      authorizationEnv: "TOKEN",
    }),
  ).toThrow("must use HTTPS");
  expect(() =>
    validateConfig({
      source: "https://user:password@api.example.com/iam/catalog/casl.ts",
      output: "src/generated.ts",
    }),
  ).toThrow("must not contain credentials");
});

it("rejects the configuration file as generated output", async () => {
  const cwd = await project();
  await writeFile(
    resolve(cwd, "better-auth-ac.json"),
    '{"source":"https://api.example.com/casl.ts","output":"better-auth-ac.json"}\n',
  );

  await expect(pullPolicy({ cwd, fetch: vi.fn() as unknown as typeof fetch })).rejects.toThrow(
    "must not overwrite better-auth-ac.json",
  );
});

it.skipIf(process.platform === "win32")("rejects output through an external symlink", async () => {
  const cwd = await project();
  const outside = await project();
  await configure(cwd);
  await symlink(outside, resolve(cwd, "src"));

  await expect(pullPolicy({ cwd, fetch: vi.fn() as unknown as typeof fetch })).rejects.toThrow(
    "must stay inside the project directory",
  );
});
